### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by Blauschirm** [factoriommo/factorio-multienv-ctl#13]
Couldn't you get the latest version from [](https://updater.factorio.com/get-available-versions) and run the postinst script on the biggest 15.x version you found when someone calls "factorio update"? That way you only have to rebuild and publish the debian package at every major launch and the users (me :D) wouldn't have to wait to update their server and could even set up a cron task to check for updates every hour or so.

I really love your project apart from the hardcoded game version! =)

**Comment by psihius** [comment]
And you lose the ability to downgrade when update causes issues - that's the main reason we do it manually. We also add reference to the forum post so people can read up on updates and do proper urgency marking.

**Comment by Blauschirm** [comment]
Of course you could downgrade. If downgrading means just installing an older package over your current install, you can still just do that after you upgraded. The upgrade function wouldn't touch the apt package. One could even add a downgrade function along with the upgrade function. Right now I am manually replacing the bin and data folder to upgrade the server, because all my players get upgraded to latest beta by steam minutes after the release, but manually  repacking and distributing a whole apt package can never be as fast :D . I just thought that would be nice to automate.

**Comment by maikelwever** [comment]
One of the ideas we had was creating a Python script or similar that manages the installed Factorio binaries, and which gets called by the Debian package to install/update if no server is installed.

This would also allow users to switch between stable and experimental more easily.
