### ISSUE TITLE
curl not standard in ubuntu

### ISSUE THREAD

**Issue by primedead** [factoriommo/factorio-multienv-ctl#2]
curl is not default installed in ubuntu 16.10 don't know about other versions. might want to add that to the install instructions.

**Comment by psihius** [comment]
Suggest to switch to wget - same result with:
``` wget -q -O - $url```
This outputs to STDOUT

**Comment by maikelwever** [comment]
The prepared package depends on curl. I'd heavily recommend using the prebuilt package if using an apt based distro using systemd (which ubuntu 16.10 should be)

`Pre-Depends: bash,bsdtar,curl,grep,systemd,ca-certificates`

**Comment by maikelwever** [comment]
Ah nvm, I get it now. Has been fixed.
