### ISSUE TITLE
http://repo.factoriommo.org/ is not available

### ISSUE THREAD

**Issue by Koldar** [factoriommo/factorio-multienv-ctl#21]
When trying to install the package, the url specified is not reachable anymore.
Is there a way to install the package?

**Comment by Koldar** [comment]
If the external site cannot be turned on anymore, it would be nice to create a release of the package on github: in this way at the least the prebuilt `deb` wuld be publicly available.

**Comment by psihius** [comment]
To be honest, I haven't updated available versions in years. If @maikelwever comes online so we can figure out something, I can maybe redo the building and publishing.

**Comment by Koldar** [comment]
I try to create a distributed package and make a release of it: if I can do it, it may render the external site useless

**Comment by maikelwever** [comment]
I haven't played Factorio in years, but I can confirm repo.factoriommo.org is not coming back.

Using GitHub actions to push package to releases page would be a good idea if people still feel this package is useful.

Feel free to submit MRs
