### ISSUE TITLE
Error on attempt to run for first time

### ISSUE THREAD

**Issue by innominata** [factoriommo/factorio-multienv-ctl#4]
root@orange:/opt/factorio# factorio start
Could not find factorio config file: /opt/factorio/config/config.ini
If this is the first time you run this script; You might need to generate the config.ini
by running: sudo -u factorio /opt/factorio/bin/x64/factorio --start-server factorio-init-save

**Comment by psihius** [comment]
@maikelwever i'd say because we have a default instance, we could internally run factorio with default settings, stop it and delete newly created save file. It's a bit annoying to do this by hand.

**Comment by innominata** [comment]
its not looking in a multienv-ctl specific directory, I'll investigate further

**Comment by innominata** [comment]
may have been a previous helper, possibly factorio-init that I had installed. working now :)
