### ISSUE TITLE
Push 0.15.3 update

### ISSUE THREAD

**Issue by psihius** [factoriommo/factorio-multienv-ctl#5]
@maikelwever I have pushed the 0.15.3 update to the repository, can you please push the .deb update to the repo? We need it ASAP for this evening.

**Comment by maikelwever** [comment]
It is in the repositories now ;)

http://repo.factoriommo.org/pool/main/f/factorio-multienv-ctl/factorio-multienv-ctl_0.15.3_amd64.deb

**Comment by psihius** [comment]
@maikelwever come later to the Discord and let's figure out stuff so I don't have to bother you by such minute details.
