### ISSUE TITLE
.deb package 0.15.4 didn't update properly

### ISSUE THREAD

**Issue by psihius** [factoriommo/factorio-multienv-ctl#7]
root at factoriommo in /var/factorio/instances/public
$ apt-get install factorio-multienv-ctl
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be upgraded:
  factorio-multienv-ctl
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 12.7 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://repo.factoriommo.org/ jessie/main factorio-multienv-ctl amd64 0.15.4 [12.7 kB]
Fetched 12.7 kB in 0s (146 kB/s)
Reading changelogs... Done
(Reading database ... 45651 files and directories currently installed.)
Preparing to unpack .../factorio-multienv-ctl_0.15.4_amd64.deb ...
Unpacking factorio-multienv-ctl (0.15.4) over (0.15.3) ...
Setting up factorio-multienv-ctl (0.15.4) ...
 => The requested factorio version or newer is already installed: v0.15.3

Something went wrong here :\

**Comment by maikelwever** [comment]
Does `dpkg-reconfigure factorio-multienv-ctl` make it download the binaries?

**Comment by psihius** [comment]
No, same
`root at factoriommo in /var/factorio/instances/public
$ dpkg-reconfigure factorio-multienv-ctl
 => The requested factorio version or newer is already installed: v0.15.3
`
For some reason the postinstall script is not containing the proper version in it, like it updated the changelog and run the update and not included the second commit I did that changed the version.

**Comment by maikelwever** [comment]
@psihius try apt-get update && apt-get upgrade again, I bumped the version in the hope of fixing the odd gitlab merge commit

Else just run the following to workaround this until we get around fixing this:

```export SERVER_VERSION="0.15.4" 
export SERVER_DL_URL="https://www.factorio.com/get-download/$SERVER_VERSION/headless/linux64" 
curl --progress-bar -L "$SERVER_DL_URL" | bsdtar xf - -C /opt/factorio/```

**Comment by psihius** [comment]
Yep, that fixed it
```shell
root at factoriommo in /var/factorio/instances/public
$ /opt/factorio/factorio/bin/x64/factorio --version
Version: 0.15.4 (build 29262, linux64, headless)
Binary version: 64
Map input version: 0.12.0-0
Map output version: 0.15.4-2
```
